# Load files

In [3]:
import numpy as np
import pandas as pd

In [1]:
data = pd.read_csv("Call.csv")
data

NameError: name 'pd' is not defined

# Arrays

In [17]:
A = np.array([[1, 2],[3, 4],[5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#Matrix multiplication
B = np.array([[1, 1],[1, 1]])
C = np.matmul(A,B)
C

array([[ 3,  3],
       [ 7,  7],
       [11, 11]])

In [16]:
#Element wise multiplication
D = C * A
D

array([[ 3,  6],
       [21, 28],
       [55, 66]])

In [21]:
#Vectorized operations
E = np.exp(D)
F = D**2
print(E)
print(F)

[[2.00855369e+01 4.03428793e+02]
 [1.31881573e+09 1.44625706e+12]
 [7.69478527e+23 4.60718663e+28]]
[[   9   36]
 [ 441  784]
 [3025 4356]]


In [26]:
v = np.array([[1],[2],[3]])
1.0/v

array([[1.        ],
       [0.5       ],
       [0.33333333]])

In [36]:
v > 2

array([[False],
       [False],
       [ True]])

In [28]:
#Array with zeros
Z =np.zeros((3,2))
Z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
#Array with ones
O =np.ones((2,4))
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# identity matrix
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#transpose
np.transpose(O)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
#maximum value
print(E)
np.max(E)

[[2.00855369e+01 4.03428793e+02]
 [1.31881573e+09 1.44625706e+12]
 [7.69478527e+23 4.60718663e+28]]


4.607186634331292e+28

In [39]:
#find the elements that fulfill a condition by row and column
print(F)
np.where(F < 500)

[[   9   36]
 [ 441  784]
 [3025 4356]]


(array([0, 0, 1]), array([0, 1, 0]))

In [42]:
#add all elements
print(I)
np.sum(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3.0

In [44]:
#slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
arr[0:2, 1:4] #from rows 0 and 1 take columns 1 to 3

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[2, 3, 4],
       [7, 8, 9]])

In [49]:
np.max(arr[:,2]) #find the maximum of column 2

8

In [52]:
arr.sum(axis=0) #sum by column

array([ 7,  9, 11, 13, 15])

In [53]:
arr.sum(axis=1) #sum by row

array([15, 40])

In [57]:
H = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.trace(H) #sum elements in the diagonal

15

In [59]:
#Create random array
R = np.random.rand(3,2)
R

array([[0.84850449, 0.14745329],
       [0.84480054, 0.71048984],
       [0.96842993, 0.11944565]])